ai_model:
  similarity_threshold: 0.75
  use_clustering: true
  use_outlier_filter: true
cns_rules:
  hba_max: 10
  hbd_max: 5
  logp_max: 5
  logp_min: -3
  mw_max: 500
  mw_min: 150
  rotb_max: 10
  tpsa_max: 90
data:
  library_csv: data/mitophagy_library_2k/library.csv
  references_csv: data/references.csv
filters:
  cns_filter: true
  cns_rules:
    hba_max: 12
    hbd_max: 7
    logp_max: 5.5
    logp_min: -7
    mw_max: 725
    mw_min: 130
    rotb_max: 11
    tpsa_max: 200
  pains: true
fingerprints:
  morgan_nbits: 2048
  morgan_radius: 2
mol2vec:
  model_path: models/mol2vec_model.pkl
output:
  dir: mit_outputs/mit_2k_ultrafast_20251015_185131
  hits_csv: screening_hits.csv
  report_txt: screening_report.txt
performance:
  chunk_size: 10000
  max_results: 50000
  use_streaming: false
shape3d:
  max_attempts: 50
  num_confs: 5
  prune_rms_thresh: 0.5
  seed: 42
  use_mmff: true
similarity:
  w_1d: 0.33
  w_2d: 0.34
  w_3d: 0.33
